export const ADD_ELEMENT = "ADD_ELEMENT";
export const UPDATE_ELEMENT = "UPDATE_ELEMENT";
export const REMOVE_ELEMENT = "REMOVE_ELEMENT";
export const SET_ACTIVE_ELEMENT = "SET_ACTIVE_ELEMENT";
export const SET_BACKGROUND = "SET_BACKGROUND";
export const TOGGLE_PREVIEW = "TOGGLE_PREVIEW";

export const SET_LINKEDIN_FORM_DATA = "SET_LINKEDIN_FORM_DATA";
export const GENERATE_CERTIFICATE_ID = "GENERATE_CERTIFICATE_ID";
export const TOGGLE_LINKEDIN_PREVIEW = "TOGGLE_LINKEDIN_PREVIEW";

export const SET_UDEMY_FORM_DATA = "SET_UDEMY_FORM_DATA";
export const GENERATE_UDEMY_CERTIFICATE_ID = "GENERATE_UDEMY_CERTIFICATE_ID";
export const TOGGLE_UDEMY_PREVIEW = "TOGGLE_UDEMY_PREVIEW";

export const SET_BADGE = "SET_BADGE";
export const CLEAR_BADGE = "CLEAR_BADGE";
export const ADD_QR_CODE = "ADD_QR_CODE";
